export const mailActionTypes = {
  SET_SEND_MESSAGE_OPEN: "SET_OPEN_MESSAGE_OPEN",
  CLOSE_SEND_MESSAGE: "CLOSE_SEND_MESSAGE",
  FETCH_EMAILS_START: "FETCH_EMAILS_START",
  FETCH_EMAILS_SUCCESS: "FETCH_EMAILS_SUCESS",
  FETCH_EMAILS_FAILURE: "FETCH_EMAILS_FAILURE",
  FETCH_EMAIL_BY_ID: "FETCH_EMAIL_BY_ID",
};
